### ISSUE TITLE
Сегодня вечером буду проверять

### ISSUE THREAD

**Issue by TonitaN** [Postlog/FLT-Lab-2#30]
Причём буду проверять по веткам. Если вы хотите, чтобы проверка прошла адекватно, то надо:
- привести работу в максимально автономный вид (написать краткие комментарии, какие функции работают автономно и привести примеры запуска)
- после чего оставить здесь комментарий, что ваша ветка готова к проверке

**Comment by TonitaN** [comment]
??? Нет готовых к проверке или забыли здесь отметиться?

**Comment by pollykon** [comment]
Добрый день! я занималась производными и накачкой. поскольку производные антимирова и брзозовски - функции, которые не зависят от других участников команды, их я реализовала. однако с длиной накачки дела обстоят сложнее. логику перебора инфиксов по префиксам я сделала, однако до самого ответа дойти не могу и протестировать логику кода, поскольку у нас отсутствуют рабочие версии детерминизации и сабсета. в связи с чем вопрос, что делать в данной ситуации. я могу найти чужую реализацию данных функций и добавить их к себе, чтобы дойти всё-таки до ответа. либо же оставить данную функцию и отправить на проверку только производные.

**Comment by TonitaN** [comment]
С накачкой в принципе можете не мучиться, раз такая ситуация. За производные, если всё адекватно, дам 5 баллов.

**Comment by Kekega** [comment]
Доброго времени суток. Я занимался (в основном) визуализацией имеющихся функций, хотя имеется их не много. В файле [animate_list.py](https://github.com/Postlog/FLT-Lab-2/blob/vizualization_with_ipynb/visualization_utils/animate_list.py) находится функция, которая визуализирует автоматы или вообще любые объекты для которых определен метод __repr__, в частности любые строковые сообщения, а также графы или автоматы, для которых мною был реализован метод a_step (для объекта FiniteAutomaton). Функция должна была быть использована для пошаговой визуализации алгоритмов. Также реализован объект графа (который возможно никому так и не понадобился, но я его хоть для примера в ноутбуке использовал). 
Примеры работы можно посмотреть в ноутбуке [vizualization.ipynb](https://github.com/Postlog/FLT-Lab-2/blob/vizualization_with_ipynb/vizualization.ipynb), в качестве примеров представлена анимация просто строкового списка, dfs алгоритма на графе и метода _unify для метода subset для автоматов(проверять работу метода subset в этой ветке не стоит). В теории визуализировать можно любой алгоритм ~~если реализовать этот алгоритм~~.

**Comment by EliseySoft** [comment]
Добрый день! Я занимался тайпчекером. Реализовал статический и динамический тайпчекер, а также вспомогательные функции для них. Однако тайпчекер работает только в теории, так как не реализованы некоторые функции для его полноценной проверки. Я могу сделать заглушки для этих функций и протестировать только статический тайпчекер, так как для динамического нужна полная реализация отсутствующих функций.

**Comment by pollykon** [comment]
Ветка для производных: pump-length
Чтобы запустить: python3 main.py < <имя_файла>
Далее необходимо ввести регулярное выражение и символ, по которому берется производная.

**Comment by PROCENTX123** [comment]
Добрый вечер! Я занимался утилитами. Из функций реализовал детерминизацию, удаление эпсилон правил, минимизацию, reverse, or для НКА ,а также функции and, or, xor для ДКА.
Ветка для методов: method.
Чтобы запустить: python3 nfa.py раскомментировать нужный функционал.

**Comment by alien-agent** [comment]
Здравствуйте! Мой код лежит в ветке main, файлы:

- functions/minimal.py
- functions/subset.py
- functions/equiv.py
- functions/bisim.py
- models/grammar.py

**Comment by Pug-coder** [comment]
Добрый вечер! Занимался автоматами. Реализован только Томпсон.
код в ветке main  functions/thompson

**Comment by TonitaN** [comment]
> Здравствуйте! Мой код лежит в ветке main, файлы:

> Добрый вечер! Занимался автоматами. Реализован только Томпсон. код в ветке main functions/thompson

@Pug-coder , @alien-agent , примеры запуска тоже скиньте, пожалуйста.

**Comment by TonitaN** [comment]
Метод `__str__` для автоматов: да кому я вообще нужен?
Народ, исправляйте срочно, не буду я за вас его реализовывать.

**Comment by TonitaN** [comment]
> Добрый день! Я занимался тайпчекером. Реализовал статический и динамический тайпчекер, а также вспомогательные функции для них. Однако тайпчекер работает только в теории, так как не реализованы некоторые функции для его полноценной проверки. Я могу сделать заглушки для этих функций и протестировать только статический тайпчекер, так как для динамического нужна полная реализация отсутствующих функций.

Мне понравилась идея с `typing`, но различия между обработкой DFA и NFA я не нашла.

**Comment by TonitaN** [comment]
Н-да, у вас был самый богатый инструментарий, и все возможности сделать всё быстро и красиво, используя опыт соседей и достижения цивилизации. Но гора родила мышь...

Печально, что так получилось с проектом, а главное, что этот язык не смогли взять другие, кто довёл бы проект хотя бы до пре-альфа.

В ветке визуализации нашла только метод визуализации, а не порождение хоть какого-нибудь ipynb-файла.

**Comment by Pug-coder** [comment]
> Метод `__str__` для автоматов: да кому я вообще нужен?
> Народ, исправляйте срочно, не буду я за вас его реализовывать.


Метод добавил, спасибо за коментарий. 
Пример запуска также есть (test.py)

**Comment by PROCENTX123** [comment]
> Метод `__str__` для автоматов: да кому я вообще нужен? Народ, исправляйте срочно, не буду я за вас его реализовывать.

Метод добавил.
Изменения на ветке method.

**Comment by TonitaN** [comment]
`DFA.normalize` - это весело ((
В общем, баллы я по своему разумению добавила, и больше ничего спрашивать или требовать в этой теме ни у кого не буду, т.к. если народ не озаботился тем, чтобы я могла нормально проверить их функционал, то мне тем более не интересно этим заниматься.
